export default [
  {
    trainID: 1,
    trainType: 'freight',
    trainSeries: 'GP9',
    trainDate: 1954,
    trainBuilderID: 1,
    trainBuilder: 'EMD',
    trainBuilderHQ: 'Chicago',
    trainBuilderState: 'IL',
  },
  {
    trainID: 2,
    trainType: 'passenger',
    trainSeries: 'F3',
    trainDate: 1955,
    trainBuilderID: 1,
    trainBuilder: 'EMD',
    trainBuilderHQ: 'Chicago',
    trainBuilderState: 'IL',
  },
  {
    trainID: 3,
    trainType: 'freight',
    trainSeries: 'ES44AC',
    trainDate: 2003,
    trainBuilderID: 2,
    trainBuilder: 'GE',
    trainBuilderHQ: 'Boston',
    trainBuilderState: 'MA',
  },
  {
    trainID: 4,
    trainType: 'passenger',
    trainSeries: 'AMD103',
    trainDate: 1992,
    trainBuilderID: 2,
    trainBuilder: 'GE',
    trainBuilderHQ: 'Boston',
    trainBuilderState: 'MA',
  },
  {
    trainID: 5,
    trainType: 'passenger',
    trainSeries: 'PA',
    trainDate: 1946,
    trainBuilderID: 3,
    trainBuilder: 'ALCO',
    trainBuilderHQ: 'Schenectady',
    trainBuilderState: 'NY',
  },
];
